### ISSUE TITLE
Does not work - iTunes updated the path to cover URLs. Can you please fix?

### ISSUE THREAD

**Issue by mR12KL** [sparanoid/itunes-artwork-grabber#2]
Hi,

http://is5.mzstatic.com/image/thumb/Music62/v4/8b/21/7f/8b217f3d-7a6a-f6d2-ae6d-5ae6d42b46fd/source/170x170bb.jpg

This is the new format of iTunes cover links. Can you please update the code for Chrome? I'm sure it's a simple fix. Thanks!

**Comment by sparanoid** [comment]
Hi @mR12KL thanks for reporting, I'm aware of this issue and it should be fixed in the next release.
