### ISSUE TITLE
iTunes updated their website and this no longer works!

### ISSUE THREAD

**Issue by mR12KL** [sparanoid/itunes-artwork-grabber#4]
Hi,

Today iTunes updated their website, and this script is no longer functional. Please update! I use this everyday!!

**Comment by sparanoid** [comment]
It seems Apple only updated page layout for Music, I'll look into this later.

**Comment by mR12KL** [comment]
Any ETA on this?

**Comment by Rubinetto** [comment]
Any news?

**Comment by mR12KL** [comment]
I have no idea. It's unfortunate an app as simple and as great as this hasn't recieved the repairs it deserves :(
