### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by stayxnegative** [sparanoid/itunes-artwork-grabber#7]
The chrome extension is no longer stable, when you go to a music page, the text "view artwork in new tab" appears and then immediately disappears. You have to manually refresh the page dozens of times until the text will stay on the page, and then when you click it, it only loads a 268px x 268px sized image (https://is4-ssl.mzstatic.com/image/thumb/Music118/v4/0a/34/bc/0a34bc44-e534-c881-1a6c-fc43817d7415/616892506744.jpg/268x0w.jpg).

**Comment by sparanoid** [comment]
Fixed in latest version
